console.log('***************************');
console.log('#      Token Generator    #');
console.log('***************************');
console.log('');
console.log(Math.random().toString(36).substring(7));
console.log(Math.random().toString(36).substring(7));
console.log(Math.random().toString(36).substring(7));
console.log(Math.random().toString(36).substring(7));
console.log(Math.random().toString(36).substring(7));
console.log('');
